### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 003snow** [Stents-/XOutput#25]
I could not find windows 306 controller driver. All the links are 404s now. But i tried downloading as close to a 360 driver as i could. i got Xoutput 0.11 and followed the steps. Launched it from steam, try to connect by pressing start and get this error (continue does nothing) 

Unhandled exception had occured in your application.

E_NOTIMPL: The function called is not supported at this time (-2147467263)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
SlimDX.DirectInput.DirectInputException: E_NOTIMPL: The function called is not supported at this time (-2147467263)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.DirectInput.DeviceProperties.get_InstanceName()
   at XOutput.ControllerManager.detectControllers()
   at XOutput.ControllerManager.Start()
   at XOutput.XOut.StartStopBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

XOutput
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
##     CodeBase: file:///C:/Users/Cheslav/Desktop/Xoutput/XOutput.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
##     CodeBase: file:///C:/Users/Cheslav/Desktop/Xoutput/SlimDX.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by lballardini** [comment]
I've got the same problem here. 
Was running fine on another system before.

**Comment by lballardini** [comment]
Okay i got it fixed now: it's a missing dependecie you will have to install first: 
https://slimdx.org/download.php
